version: '3.9'

services:
  #MongoDB services
  mongo_db:
    image: mongo:latest
    restart: always
    ports: 
      - 27017:27017
    volumes: 
      - mongo_db:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: certified_opinion
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:debug # override entry command
volumes: 
  mongo_db: {}